import "./globals.css";
import { Navigation } from "./components/Navigation";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Marvel API",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-beaufort leading-normal tracking-[2px]">
        <Navigation />
        {children}
      </body>
    </html>
  );
}
