import "./globals.css";
import { Navigation } from "./components/Navigation";

export const metadata = {
  title: "Marvel API",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-beaufort leading-normal tracking-[2px] bg-[url('/background.webp')] bg-no-repeat bg-cover w-full h-full">
        <Navigation />
        {children}
      </body>
    </html>
  );
}
